- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - add_host:
      name: bastion.cvdbf.sandbox526.opentlc.com
      groups: bastions
      ansible_user: ec2-user
      ansible_ssh_private_key_file: ~/.ssh/opentlc_admin_backdoor.pem
      ansible_ssh_extra_args: -o StrictHostKeyChecking=no

- hosts: bastions
  gather_facts: false
  tasks:
  - name: Ensure htpasswd Secret is absent
    k8s:
      state: absent
      api_version: v1
      kind: Secret
      name: htpasswd-secret
      namespace: openshift-config
