- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - add_host:
      name: bastion.9bt9l.sandbox668.opentlc.com
      groups: bastions
      ansible_user: ec2-user
      ansible_ssh_private_key_file: ~/.ssh/opentlc_admin_backdoor.pem
      ansible_ssh_extra_args: -o StrictHostKeyChecking=no

  - command: >-
      ansible-galaxy install
      -r {{ playbook_dir }}/r.yml

  - command: >-
      ansible-galaxy collection install
      -r {{ playbook_dir }}/r.yml
      --force-with-deps

- hosts: bastions
  run_once: true
  gather_facts: false
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/{{ cluster_name }}/auth/kubeconfig
  vars:
    cluster_name: cluster-9bt9l
  tasks:
  - include_tasks: tasks.yml
