- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - add_host:
      name: bastion.rlc6c.sandbox1323.opentlc.com
      groups: bastions
      ansible_user: ec2-user
      ansible_ssh_private_key_file: ~/.ssh/opentlc_admin_backdoor.pem
      ansible_ssh_extra_args: -o StrictHostKeyChecking=no

  - set_fact:
      cluster_name: cluster-rlc6c

- hosts: bastions
  gather_facts: false
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/{{ cluster_name }}/auth/kubeconfig
  tasks:
  - name: Set Ansible Python interpreter to k8s virtualenv
    set_fact:
      ansible_python_interpreter: /opt/virtualenvs/k8s/bin/python

  - name: Ensure htpasswd Secret is absent
    k8s:
      state: absent
      api_version: v1
      kind: Secret
      name: htpasswd-secret
      namespace: openshift-config
